version: "3.9"
services:
  frontend:
   build:
    context: ./frontend
    dockerfile: Dockerfile
   ports:
    - 3000:3000
   container_name: react-ui
   networks:
    - mern-stack-net
   volumes:
    - ./frontend/src:/usr/app/src
    - ./frontend/public:/usr/app/public
   depends_on:
    - backend
   stdin_open: true
   tty: true

  backend:
   build:
    context: ./backend
    dockerfile: Dockerfile
   ports:
    - 8080:8080
   container_name: node-api
   environment:
    MONGO_URI: "mongodb://mongo-db:27017/images_uploader"
   networks:
    - mern-stack-net
   volumes:
    - ./backend/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    hostname: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local